version: "3.7"

services:
  database_qwho:
    image: postgres
    container_name: database_qwho
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=qwho
    volumes:
      - pgdata:/data/postgres
    network_mode: host

volumes: 
  pgdata:
    driver: local